<?php 
	echo form_open('register/create');
	echo '<table>'.'<tr>'.'<td>';
	echo form_label('User', 'username');
	echo '</td>'.'<td>';
	echo form_input('username');
	echo '</td>'.'</tr>'.'<tr>'.'<td>';
	echo form_label('Password', 'password');
	echo '</td>'.'<td>';
	echo form_password('password');
	echo '</td>'.'</tr>'.'<tr>'.'<td>';
	echo form_label('First Name', 'fname');
	echo '</td>'.'<td>';
	echo form_input('fname');
	echo '</td>'.'</tr>'.'<tr>'.'<td>';
	echo form_label('Last Name', 'lname');
	echo '</td>'.'<td>';
	echo form_input('lname');
	echo '</td>'.'</tr>'.'<tr>'.'<td>';
	echo form_label('Telephone', 'tel');
	echo '</td>'.'<td>';
	echo form_input('tel');
	echo '</td>'.'</tr>'.'<tr>'.'<td>';
	echo form_label('E-mail', 'email');
	echo '</td>'.'<td>';
	echo form_input('email');
	echo '</td>'.'</tr>'.'<tr>'.'<td>';
	echo form_submit('mysubmit', 'Submit');
	echo '</td>'.'<td>'.'&nbsp;'.'</td>'.'</tr>'.'</table>';
?>